module.exports = Object.freeze({
    SERVER: "http://localhost:3000",
    AUTH_USER: "09f009efe7b9ae",
    AUTH_PASS: "cd1233a2d8d6a7",
    AUTH_FROM: "oanapopescu93@gmail.com",
    SERVER_TABLES: [
        {table_id: '001', table_name: "roulette", table_type: "european"},
        {table_id: '002', table_name: "roulette", table_type: "american"},
        {table_id: '003', table_name: "roulette", table_type: "european"},
        {table_id: '004', table_name: "roulette", table_type: "american"},
        {table_id: '001', table_name: "blackjack"},
        {table_id: '002', table_name: "blackjack"},
        {table_id: '003', table_name: "blackjack"},
        {table_id: '001', table_name: "slots"},
        {table_id: '002', table_name: "slots"},
        {table_id: '003', table_name: "slots"},
        {table_id: '004', table_name: "slots"},
        {table_id: '005', table_name: "slots"},
    ],
    SERVER_MARKET: [
        {id: "item01", name: "Item 01", description: "item 01 description", price: 1},
        {id: "item02", name: "Item 02", description: "item 02 description", price: 2},
        {id: "item03", name: "Item 03", description: "item 03 description", price: 3},
        {id: "item04", name: "Item 04", description: "item 04 description", price: 4},
        {id: "item05", name: "Item 05", description: "item 05 description", price: 5},
        {id: "item06", name: "Item 06", description: "item 06 description", price: 6},
        {id: "item07", name: "Item 07", description: "item 07 description", price: 7},
        {id: "item08", name: "Item 08", description: "item 08 description", price: 8},
        {id: "item09", name: "Item 09", description: "item 09 description", price: 9},
        {id: "item10", name: "Item 10", description: "item 10 description", price: 10},
        {id: "item11", name: "Item 11", description: "item 11 description", price: 11},
        {id: "item12", name: "Item 12", description: "item 12 description", price: 12},
        {id: "item13", name: "Item 13", description: "item 13 description", price: 13},
        {id: "item14", name: "Item 14", description: "item 14 description", price: 14},
        {id: "item15", name: "Item 15", description: "item 15 description", price: 15},
        {id: "item16", name: "Item 16", description: "item 16 description", price: 16},
    ],
    MONEY: 100,
    SESS_USERS: [
        {id: 0, user: "aaa", email: "aaaaaa@gmail.com", pass: "aaa"},
        {id: 1, user: "bbb", email: "bbbbbb@gmail.com", pass: "bbb"},
        {id: 3, user: "ccc", email: "cccccc@gmail.com", pass: "ccc"},
    ],
})