module.exports = Object.freeze({
    PRODUCTS: [
        {table_id: '001', table_name: "roulette", table_type: "european"},
        {table_id: '002', table_name: "roulette", table_type: "american"},
        {table_id: '003', table_name: "roulette", table_type: "european"},
        {table_id: '004', table_name: "roulette", table_type: "american"},
        {table_id: '005', table_name: "roulette", table_type: "european"},
        {table_id: '006', table_name: "roulette", table_type: "american"},
        {table_id: '007', table_name: "roulette", table_type: "european"},
        {table_id: '008', table_name: "roulette", table_type: "american"},
        {table_id: '009', table_name: "roulette", table_type: "european"},
        {table_id: '010', table_name: "roulette", table_type: "american"},
        {table_id: '011', table_name: "roulette", table_type: "european"},
        {table_id: '012', table_name: "roulette", table_type: "american"},
        {table_id: '013', table_name: "roulette", table_type: "european"},
        {table_id: '014', table_name: "roulette", table_type: "american"},
        {table_id: '015', table_name: "roulette", table_type: "european"},
        {table_id: '016', table_name: "roulette", table_type: "american"},

        {table_id: '017', table_name: "blackjack", table_type: "table_1"},
        {table_id: '018', table_name: "blackjack", table_type: "table_2"},
        {table_id: '019', table_name: "blackjack", table_type: "table_3"},
        {table_id: '020', table_name: "blackjack", table_type: "table_4"},
        {table_id: '021', table_name: "blackjack", table_type: "table_5"},
        {table_id: '022', table_name: "blackjack", table_type: "table_6"},
        {table_id: '023', table_name: "blackjack", table_type: "table_7"},
        {table_id: '024', table_name: "blackjack", table_type: "table_8"},

        {table_id: '025', table_name: "slots", table_type: "reel_3"},
        {table_id: '026', table_name: "slots", table_type: "reel_5"},
        {table_id: '027', table_name: "slots", table_type: "reel_3"},
        {table_id: '028', table_name: "slots", table_type: "reel_5"},
        {table_id: '029', table_name: "slots", table_type: "reel_3"},
        {table_id: '030', table_name: "slots", table_type: "reel_5"},
        {table_id: '031', table_name: "slots", table_type: "reel_3"},
        {table_id: '032', table_name: "slots", table_type: "reel_5"},

        {table_id: '033', table_name: "craps", table_type: "table_1"},
        {table_id: '034', table_name: "craps", table_type: "table_2"},
        {table_id: '035', table_name: "craps", table_type: "table_3"},
        {table_id: '036', table_name: "craps", table_type: "table_4"},
        {table_id: '037', table_name: "craps", table_type: "table_5"},
        {table_id: '038', table_name: "craps", table_type: "table_6"},
        {table_id: '039', table_name: "craps", table_type: "table_7"},
        {table_id: '040', table_name: "craps", table_type: "table_8"},

        {table_id: '041', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '042', table_name: "poker", table_type: "poker_5_card_draw"},
        {table_id: '043', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '044', table_name: "poker", table_type: "poker_5_card_draw"},
        {table_id: '045', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '046', table_name: "poker", table_type: "poker_5_card_draw"},
        {table_id: '047', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '048', table_name: "poker", table_type: "poker_5_card_draw"},
        {table_id: '049', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '050', table_name: "poker", table_type: "poker_5_card_draw"},
        {table_id: '051', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '052', table_name: "poker", table_type: "poker_5_card_draw"},
        {table_id: '053', table_name: "poker", table_type: "poker_texas_holdem"},
        {table_id: '054', table_name: "poker", table_type: "poker_5_card_draw"},

        {table_id: '055', table_name: "baccarat", table_type: "table_1"},
        {table_id: '056', table_name: "baccarat", table_type: "table_2"},
        {table_id: '057', table_name: "baccarat", table_type: "table_3"},
        {table_id: '058', table_name: "baccarat", table_type: "table_4"},
        {table_id: '059', table_name: "baccarat", table_type: "table_5"},
        {table_id: '060', table_name: "baccarat", table_type: "table_6"},
        {table_id: '061', table_name: "baccarat", table_type: "table_7"},
        {table_id: '062', table_name: "baccarat", table_type: "table_8"},
    ],
    MARKET: [
        {id: "carrot", name_eng: "carrot", name_ro: "morcov", name_fr: "carotte", name_de: "karotte", name_es: "zanahoria", name_it: "carota", name_pt: "cenoura", name_ru: "морковь", name_zh: "胡萝卜", price: 1, value: 1},
        {id: "garlic", name_eng: "garlic", name_ro: "usturoi", name_fr: "ail", name_de: "knoblauch", name_es: "ajo", name_it: "aglio", name_pt: "alho", name_ru: "чеснок", name_zh: "大蒜", price: 2, value: 2},
        {id: "onion", name_eng: "onion", name_ro: "ceapa", name_fr: "oignon", name_de: "zwiebel", name_es: "cebolla", name_it: "cipolla", name_pt: "cebola", name_ru: "лук", name_zh: "洋葱", price: 3, value: 3},
        {id: "radish", name_eng: "radish", name_ro: "ridiche", name_fr: "radis", name_de: "radieschen", name_es: "rábano", name_it: "ravanello", name_pt: "rabanete", name_ru: "редис", name_zh: "萝卜", price: 5, value: 5},
        {id: "turnip", name_eng: "turnip", name_ro: "nap", name_fr: "navet", name_de: "steckrübe", name_es: "nabo", name_it: "rape", name_pt: "nabo", name_ru: "репа", name_zh: "芜菁", price: 10, value: 10},
        {id: "potato", name_eng: "potato", name_ro: "cartof", name_fr: "pomme de terre", name_de: "kartoffel", name_es: "patata", name_it: "patata", name_pt: "batata", name_ru: "картофель", name_zh: "土豆", price: 20, value: 20},
        {id: "cabbage", name_eng: "cabbage", name_ro: "varza", name_fr: "chou", name_de: "kohl", name_es: "col", name_it: "cavolo", name_pt: "repolho", name_ru: "капуста", name_zh: "卷心菜", price: 30, value: 30},
    ],
    PROFILES: [
        {id: 1, name_eng: "weasel", name_ro: "nevăstuică", name_fr: "belette", name_de: "wiesel", name_es: "comadreja", name_it: "donnola", name_pt: "doninha", name_ru: "ласка", name_zh: "鼬", free: true},
        {id: 2, name_eng: "fox", name_ro: "vulpe", name_fr: "renard", name_de: "fuchs", name_es: "zorro", name_it: "volpe", name_pt: "raposa", name_ru: "лиса", name_zh: "狐狸", free: false},
        {id: 3, name_eng: "wolf", name_ro: "lup", name_fr: "loup", name_de: "wolf", name_es: "lobo", name_it: "lupo", name_pt: "lobo", name_ru: "волк", name_zh: "狼", free: false},
        {id: 4, name_eng: "lynx", name_ro: "râs", name_fr: "lynx", name_de: "luchs", name_es: "lince", name_it: "lince", name_pt: "lince", name_ru: "рысь", name_zh: "猞猁", free: false},
        {id: 5, name_eng: "ferret", name_ro: "dihor", name_fr: "furet", name_de: "frettchen", name_es: "hurón", name_it: "furetto", name_pt: "furão", name_ru: "хорёк", name_zh: "雪貂", free: true},
        {id: 6, name_eng: "marten", name_ro: "jder", name_fr: "martre", name_de: "marder", name_es: "marta", name_it: "martora", name_pt: "marta", name_ru: "кунгуря", name_zh: "貂", free: true},
        {id: 7, name_eng: "mink", name_ro: "nurcă", name_fr: "vison", name_de: "marder", name_es: "nutria", name_it: "visone", name_pt: "visão", name_ru: "нyрка", name_zh: "水貂", free: true},
        {id: 8, name_eng: "bear", name_ro: "urs", name_fr: "ours", name_de: "bär", name_es: "oso", name_it: "orso", name_pt: "urso", name_ru: "медведь", name_zh: "熊", free: false},
    ],
    DONATIONS: [
        {type: "crypto", title: "Bitcoin", text: "bc1q250h9jjr7wj9302z0vpzath3c560k3krkg0fxk", link: "bitcoin:bc1q250h9jjr7wj9302z0vpzath3c560k3krkg0fxk"},
        {type: "crypto", title: "Ethereum", text: "-"},
        {type: "crypto", title: "Litecoin", text: "-"},
        {type: "crypto", title: "Bitcoin Cash", text: "-"},
        {type: "crypto", title: "Dogecoin", text: "-"},
        {type: "paypal", title: "PaypalMe", link: "https://paypal.me/oanapopescu93?country.x=RO&locale.x=en_US"},
        {type: "paypal", title: "Paypal Donate", link: "https://www.paypal.com/donate/?hosted_button_id=FBUHUHZCKWZRA"},
        {type: "bank", title: "IBAN", text: "RO93BTRLRONCRT0316896401"}
    ],
    RACE_RABBITS: [
        {id: 1, participating: false, breed: "American Fuzzy Lop", img: "/img/rabbit_list/american_fuzzy_lop.png"},
        {id: 2, participating: false, breed: "American", img: "/img/rabbit_list/american.png"},
        {id: 3, participating: false, breed: "Belgian Hare", img: "/img/rabbit_list/belgian_hare.png"},
        {id: 4, participating: false, breed: "Dutch", img: "/img/rabbit_list/dutch.png"},
        {id: 5, participating: false, breed: "Dwarf Hotot", img: "/img/rabbit_list/dwarf_hotot.png"},
        {id: 6, participating: false, breed: "English angora", img: "/img/rabbit_list/english_angora.png"},
        {id: 7, participating: false, breed: "English Lop", img: "/img/rabbit_list/english_lop.png"},
        {id: 8, participating: false, breed: "English Spot", img: "/img/rabbit_list/english_spot.png"},
        {id: 9, participating: false, breed: "Flemish giant", img: "/img/rabbit_list/flemish_giant.png"},
        {id: 10, participating: false, breed: "Florida White", img: "/img/rabbit_list/florida_white.png"},
        {id: 11, participating: false, breed: "French Angora", img: "/img/rabbit_list/french_angora.png"},
        {id: 12, participating: false, breed: "Harlequin", img: "/img/rabbit_list/harlequin.png"},
        {id: 13, participating: false, breed: "Havana", img: "/img/rabbit_list/havana.png"},
        {id: 14, participating: false, breed: "Himalayan", img: "/img/rabbit_list/himalayan.png"},
        {id: 15, participating: false, breed: "Holland Lop", img: "/img/rabbit_list/holland_lop.png"},
        {id: 16, participating: false, breed: "Jersey Wooly", img: "/img/rabbit_list/jersey_wooly.png"},
        {id: 17, participating: false, breed: "Lionhead", img: "/img/rabbit_list/lionhead.png"},
        {id: 18, participating: false, breed: "Mini Lop", img: "/img/rabbit_list/mini_lop.png"},
        {id: 19, participating: false, breed: "Mini Rex", img: "/img/rabbit_list/mini_rex.png"},
        {id: 20, participating: false, breed: "Neatherland", img: "/img/rabbit_list/neatherland.png"},
    ],
    KENO_PRIZES: [
        [{numbers_matched: 1, win: 3}],
        [{numbers_matched: 2, win: 12}],
        [{numbers_matched: 2, win: 1}, {numbers_matched: 3, win: 44}],
        [{numbers_matched: 2, win: 1}, {numbers_matched: 3, win: 4}, {numbers_matched: 4, win: 122}],
        [{numbers_matched: 3, win: 2}, {numbers_matched: 4, win: 14}, {numbers_matched: 5, win: 640}],
        [{numbers_matched: 3, win: 1}, {numbers_matched: 4, win: 5}, {numbers_matched: 5, win: 80}, {numbers_matched: 6, win: 1800}],
        [{numbers_matched: 3, win: 1}, {numbers_matched: 4, win: 3}, {numbers_matched: 5, win: 12}, {numbers_matched: 6, win: 125}, {numbers_matched: 7, win: 5000}],
        [{numbers_matched: 4, win: 2}, {numbers_matched: 5, win: 7}, {numbers_matched: 6, win: 60}, {numbers_matched: 7, win: 675}, {numbers_matched: 8, win: 25000}],
        [{numbers_matched: 4, win: 1}, {numbers_matched: 5, win: 5}, {numbers_matched: 6, win: 20}, {numbers_matched: 7, win: 210}, {numbers_matched: 8, win: 2500}, {numbers_matched: 9, win: 30000}],
        [{numbers_matched: 4, win: 1}, {numbers_matched: 5, win: 2}, {numbers_matched: 6, win: 6}, {numbers_matched: 7, win: 50}, {numbers_matched: 8, win: 580}, {numbers_matched: 9, win: 30000}, {numbers_matched: 10, win: 50000}],
    ],
    CONTACT: [
        {
            DE: {country: "Rumänien", city: "Bukarest", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            ENG: {country: "Romania", city: "Bucharest", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            ES: {country: "Rumanía", city: "Bucarest", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            FR: {country: "Roumanie", city: "Bucarest", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            IT: {country: "Romania", city: "Bucarest", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            PT: {country: "Romênia", city: "Bucareste", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            RO: {country: "România", city: "București", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            RU: {country: "Румыния", city: "Бухарест", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
            ZH: {country: "罗马尼亚", city: "布加勒斯特", map: {lat: 44.469663, lng: 26.096306}, marker: [44.439663, 26.096306], email: "oanapopescu93@gmail.com", phone: "+40729699148", phone_text: "(+40) 729 699 148", linkedin: "https://www.linkedin.com/in/oanapopescu93", github: "https://github.com/oanapopescu93"},
        },
    ],
    COUPONS: [
        {name: "coupon01", discount: 10},
        {name: "coupon02", discount: 20},
        {name: "coupon03", discount: 30},
    ],
    FINANCES: {
        currencies: ['USD', 'EUR', 'GBP', 'CHF', 'RON'],
        min_amount_withdraw: 10000, //min amount of carrots for withdrawal
        convert_carrots_rate: 1000, // 1000 carrots = 1 usd
        min_free: 1000, //min amount where some stuff becomes free/active
    }
})